version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./resources:/app/resources
    deploy:
      resources:
        limits:
          memory: 1024M